version: "{build}"

environment:
    global:
        HAXELIB_ROOT: C:/projects/haxelib
        CYG_ROOT: C:/cygwin64
        ADD_REVISION: 1
        MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
        MYSQL_USER: root
        MYSQL_PASSWORD: Password12!
        HXBUILDS_AWS_ACCESS_KEY_ID:
          secure: fggQXlr5xGGl0znUi0UkqPWd6LviHnk0TR6YxJmuV3U=
        HXBUILDS_AWS_SECRET_ACCESS_KEY:
          secure: ewwkKcjnSKl/Vtrz1SXmI6XKk1ENmJDyzm5YaR2wi03foRhTke29TvymB21rDTSl
    matrix:
        - TEST: "macro"

skip_tags: true

install:
    - 'git submodule update --init --recursive'
    - '%CYG_ROOT%/bin/bash -lc "echo initialize"'
    - choco install curl
    - curl -fsSl https://github.com/HaxeFoundation/ocamhaxe/releases/download/1.1/ocamhaxe.zip
    - 7z x -y ocamhaxe.zip
    - cd ocamhaxe
    - config.bat

build_script:
    - 'cd %APPVEYOR_BUILD_FOLDER%'
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && make -s -f Makefile.win libs && make -j -s -f Makefile.win haxe && make -s -f Makefile.win haxelib"'
    - 'set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%'
    - 'set HAXEPATH=%APPVEYOR_BUILD_FOLDER%'
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && make -s -f Makefile.win package_bin"'
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && make -s -f Makefile.win package_choco"'
    - move out\haxe.*.nupkg .
    - dir %APPVEYOR_BUILD_FOLDER%\out
    - cd %APPVEYOR_BUILD_FOLDER%/tests/
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%/tests/
    - haxe -version
    - haxe RunCi.hxml

artifacts:
    - path: 'out/*.zip'
    - path: '*.nupkg'
